### ISSUE TITLE
Vores .vcf-kontaktfiler virker ikke med de nyeste versioner af Perls Text::vCard

### ISSUE THREAD

**Issue by nqpz** [dikurevy/RevyTeX#4]
Hvis man har en rimelig ny version af Text::vCard (fx fra pakken `libtext-vcard-perl` i Debian), får man følgende fejlbesked når man kører `make` i en revymappe med de korrekte filer:

    Kontaktliste.tex: ERROR: Either there is no END in this vCard or there is a problem with the line
    endings.  Note that the vCard RFC requires line endings delimited by \r\n
    regardless of your operating system.  Windows :crlf mode will strip out the \r
    so don't use that.

Hvis jeg bruger udgave 2.13 af Text::vCard fra 2012, kan jeg godt make.

Jeg ved ikke om de nye udgaver har en måde at slå deres pedantiske tilgang fra, men det kunne være praktisk!

**Comment by Munter** [comment]
Suk. Globale afhængigheder er røv og nøgler.

**Comment by Athas** [comment]
"Niels G. W. Serup" <notifications@github.com> writes:

> Hvis man har en rimelig ny version af Text::vCard (fx fra pakken
> `libtext-vcard-perl` i Debian), får man følgende fejlbesked når man
> kører `make` i en revymappe med de korrekte filer:
>
>     Kontaktliste.tex: ERROR: Either there is no END in this vCard or there is a problem with the line
>     endings.  Note that the vCard RFC requires line endings delimited by \r\n
>     regardless of your operating system.  Windows :crlf mode will strip out the \r
>     so don't use that.
>
> Hvis jeg bruger udgave 2.13 af Text::vCard fra 2012, kan jeg godt make.
>
> Jeg ved ikke om de nye udgaver har en måde at slå deres pedantiske
> tilgang fra, men det kunne være praktisk!

Den bedste løsning er nok at følge RFC'en.  Det er bedre end skrøbelige
hacks.

-- 
\  Troels
/\ Henriksen

**Comment by Eckankar** [comment]
Jeg kigger på det.

**Comment by Eckankar** [comment]
Jeg er enig med Troels. Jeg konverterer vores eksisterende VCF'er til DOS-format, så godtages de.
